CREATE DATABASE simpleRSS;

USE simpleRSS;

CREATE TABLE users(
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  password CHAR(50) NOT NULL,
  firstname CHAR(40) NULL DEFAULT NULL,
  lastname CHAR(40) NULL DEFAULT NULL,
  email CHAR(40) NOT NULL
);

CREATE TABLE rss_item(
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  url char(100) NOT NULL,
  user_id INT(10) UNSIGNED NOT NULL,
  FOREIGN KEY (user_id)
  REFERENCES users(id)
);
