CREATE DATABASE simpleRSS;

USE simpleRSS;

CREATE TABLE user(
  user_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  facebook_id CHAR(20) NULL DEFAULT NULL,
  password CHAR(50) NOT NULL,
  firstname CHAR(40) NULL DEFAULT NULL,
  lastname CHAR(40) NULL DEFAULT NULL,
  email CHAR(40) NOT NULL
);

CREATE TABLE wifi_spot(
  spot_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name char(100) NOT NULL,
  owner_id INT(10) UNSIGNED NOT NULL,
  password CHAR(30) NULL DEFAULT NULL,
  address CHAR(150) NULL DEFAULT NULL,
  popularity CHAR(20) NULL DEFAULT NULL,
  lat CHAR(20) NULL DEFAULT NULL,
  lng CHAR(20) NULL DEFAULT NULL,
  FOREIGN KEY (owner_id)
  REFERENCES user(user_id)
);
